export const rarityInfo = {
  common: { label: "凡品", weight: 64 },
  rare: { label: "灵品", weight: 26 },
  epic: { label: "玄品", weight: 9 },
  legendary: { label: "神品", weight: 1 },
};

export const styleInfo = {
  physical: { label: "物理", text: "直接伤害、连击、破防，成型后靠大数字爽杀。" },
  spell: { label: "法术", text: "灵气、抽牌、群体伤害，成型后连发大法术。" },
  bleed: { label: "流血", text: "叠流血后用攻击引爆，适合打 Boss。" },
  poison: { label: "中毒", text: "叠毒瘴拖回合，敌人自己掉血。" },
  control: { label: "控制", text: "离间敌人，让敌人互相攻击。" },
};

export const gradeInfo = {
  1: "初阶",
  2: "中阶",
  3: "高阶",
};

export const statusInfo = {
  burn: { label: "灼烧", text: "回合间受到伤害，结算后消退一半。" },
  bleed: { label: "流血", text: "回合间和受到攻击时都会额外受伤，伤害先扣格挡，然后减少 1 层。" },
  poison: { label: "毒瘴", text: "回合间受到伤害，然后减少 1 层。" },
  curse: { label: "诅咒", text: "受到的卡牌伤害增加。" },
  spirit: { label: "灵气", text: "提高卡牌伤害，最多 12 层；低费牌只能承载部分灵气，战斗结束后清空。" },
  chaos: { label: "离间", text: "敌人行动前触发：攻击会优先打同伴，非攻击或没有同伴则空过，然后减少 1 层。" },
  stasis: { label: "凝滞", text: "流血、毒瘴、离间将要减少层数时，先消耗凝滞并保留原状态。" },
  ward: { label: "护体", text: "抵消即将受到的伤害。" },
};

export const cards = {
  strike: {
    id: "strike",
    name: "斩妖式",
    rarity: "common",
    cost: 1,
    text: "造成 7 点伤害。",
    mythTags: ["人间"],
    effects: [{ type: "damage", target: "enemy", value: 7 }],
  },
  guard: {
    id: "guard",
    name: "护身咒",
    rarity: "common",
    cost: 1,
    text: "获得 6 点格挡。",
    mythTags: ["人间"],
    effects: [{ type: "block", target: "self", value: 6 }],
  },
  yellowCharm: {
    id: "yellowCharm",
    name: "黄符",
    rarity: "common",
    cost: 0,
    text: "造成 3 点伤害，抽 1 张牌。",
    mythTags: ["人间"],
    effects: [
      { type: "damage", target: "enemy", value: 3 },
      { type: "draw", value: 1 },
    ],
  },
  meditate: {
    id: "meditate",
    name: "调息",
    rarity: "common",
    cost: 0,
    text: "获得 1 点能量。能量已满时无法打出。",
    mythTags: ["昆仑"],
    effects: [{ type: "gainEnergy", value: 1 }],
  },
  breakArmor: {
    id: "breakArmor",
    name: "破甲符",
    rarity: "common",
    cost: 1,
    text: "造成 5 点伤害，施加 2 层诅咒。",
    mythTags: ["人间"],
    effects: [
      { type: "damage", target: "enemy", value: 5 },
      { type: "status", target: "enemy", status: "curse", stacks: 2 },
    ],
  },
  foxFire: {
    id: "foxFire",
    name: "狐火",
    rarity: "rare",
    cost: 1,
    text: "造成 5 点伤害，施加 4 层灼烧。",
    mythTags: ["妖"],
    effects: [
      { type: "damage", target: "enemy", value: 5 },
      { type: "status", target: "enemy", status: "burn", stacks: 4 },
    ],
  },
  ghostNeedle: {
    id: "ghostNeedle",
    name: "鬼针",
    rarity: "rare",
    cost: 1,
    text: "造成 4 点伤害，施加 5 层流血。",
    mythTags: ["幽冥"],
    effects: [
      { type: "damage", target: "enemy", value: 4 },
      { type: "status", target: "enemy", status: "bleed", stacks: 5 },
    ],
  },
  miasma: {
    id: "miasma",
    name: "毒瘴",
    rarity: "rare",
    cost: 1,
    text: "施加 7 层毒瘴。",
    mythTags: ["山海"],
    effects: [{ type: "status", target: "enemy", status: "poison", stacks: 7 }],
  },
  jiaoScale: {
    id: "jiaoScale",
    name: "蛟鳞",
    rarity: "rare",
    cost: 1,
    text: "获得 10 点格挡和 2 层护体。",
    mythTags: ["龙宫"],
    effects: [
      { type: "block", target: "self", value: 10 },
      { type: "status", target: "self", status: "ward", stacks: 2 },
    ],
  },
  demonMirror: {
    id: "demonMirror",
    name: "照妖镜",
    rarity: "epic",
    cost: 1,
    text: "获得 8 点格挡，施加 3 层诅咒。",
    mythTags: ["天庭"],
    effects: [
      { type: "block", target: "self", value: 8 },
      { type: "status", target: "enemy", status: "curse", stacks: 3 },
    ],
  },
  underworldPen: {
    id: "underworldPen",
    name: "幽冥判笔",
    rarity: "epic",
    cost: 2,
    text: "造成 10 点伤害，施加 6 层流血和 3 层诅咒。",
    mythTags: ["幽冥"],
    effects: [
      { type: "damage", target: "enemy", value: 10 },
      { type: "status", target: "enemy", status: "bleed", stacks: 6 },
      { type: "status", target: "enemy", status: "curse", stacks: 3 },
    ],
  },
  kunlunBreath: {
    id: "kunlunBreath",
    name: "昆仑吐纳",
    rarity: "epic",
    cost: 1,
    text: "获得 2 点灵气，抽 2 张牌。",
    mythTags: ["昆仑"],
    effects: [
      { type: "status", target: "self", status: "spirit", stacks: 2 },
      { type: "draw", value: 2 },
    ],
  },
  dragonRain: {
    id: "dragonRain",
    name: "龙宫雨",
    rarity: "epic",
    cost: 2,
    text: "对所有敌人造成 8 点伤害，施加 4 层灼烧。",
    mythTags: ["龙宫"],
    effects: [
      { type: "damage", target: "allEnemies", value: 8 },
      { type: "status", target: "allEnemies", status: "burn", stacks: 4 },
    ],
  },
  nuwaStone: {
    id: "nuwaStone",
    name: "女娲残石",
    rarity: "legendary",
    cost: 2,
    text: "回复 12 点生命，获得 3 点灵气。",
    mythTags: ["洪荒"],
    effects: [
      { type: "heal", target: "self", value: 12 },
      { type: "status", target: "self", status: "spirit", stacks: 3 },
    ],
  },
  eastBell: {
    id: "eastBell",
    name: "东皇钟影",
    rarity: "legendary",
    cost: 3,
    text: "对所有敌人造成 18 点伤害，获得 18 点格挡。",
    mythTags: ["洪荒"],
    effects: [
      { type: "damage", target: "allEnemies", value: 18 },
      { type: "block", target: "self", value: 18 },
    ],
  },
  panguMark: {
    id: "panguMark",
    name: "盘古斧痕",
    rarity: "legendary",
    cost: 2,
    text: "造成 30 点伤害。失去 6 点生命。",
    mythTags: ["洪荒"],
    effects: [
      { type: "damage", target: "enemy", value: 30 },
      { type: "loseHp", target: "self", value: 6 },
    ],
  },
  shanHaiCall: {
    id: "shanHaiCall",
    name: "山海唤形",
    rarity: "legendary",
    cost: 1,
    text: "抽 3 张牌，获得 2 点能量。",
    mythTags: ["山海"],
    effects: [
      { type: "draw", value: 3 },
      { type: "gainEnergy", value: 2 },
    ],
  },
  heavySlash: {
    id: "heavySlash",
    name: "重斩",
    rarity: "common",
    cost: 1,
    text: "造成 10 点伤害。",
    mythTags: ["人间"],
    style: "physical",
    grade: 1,
    effects: [{ type: "damage", target: "enemy", value: 10 }],
  },
  chainBlade: {
    id: "chainBlade",
    name: "连环刃",
    rarity: "rare",
    cost: 1,
    text: "连续造成 5 点伤害两次。",
    mythTags: ["人间"],
    style: "physical",
    grade: 2,
    effects: [
      { type: "damage", target: "enemy", value: 5 },
      { type: "damage", target: "enemy", value: 5 },
    ],
  },
  armyBreaker: {
    id: "armyBreaker",
    name: "破军三式",
    rarity: "epic",
    cost: 2,
    text: "造成 14 点伤害两次，施加 4 层诅咒。",
    mythTags: ["天庭"],
    style: "physical",
    grade: 3,
    effects: [
      { type: "damage", target: "enemy", value: 14 },
      { type: "damage", target: "enemy", value: 14 },
      { type: "status", target: "enemy", status: "curse", stacks: 4 },
    ],
  },
  tiangangBreak: {
    id: "tiangangBreak",
    name: "天罡破阵",
    rarity: "legendary",
    cost: 3,
    text: "对所有敌人造成 28 点伤害，获得 20 点格挡。",
    mythTags: ["天庭"],
    style: "physical",
    grade: 3,
    effects: [
      { type: "damage", target: "allEnemies", value: 28 },
      { type: "block", target: "self", value: 20 },
    ],
  },
  thunderCharm: {
    id: "thunderCharm",
    name: "雷符",
    rarity: "common",
    cost: 1,
    text: "造成 6 点伤害，获得 1 点灵气。",
    mythTags: ["天庭"],
    style: "spell",
    grade: 1,
    effects: [
      { type: "damage", target: "enemy", value: 6 },
      { type: "status", target: "self", status: "spirit", stacks: 1 },
    ],
  },
  fireRite: {
    id: "fireRite",
    name: "火德小祭",
    rarity: "rare",
    cost: 1,
    text: "对所有敌人造成 5 点伤害，施加 5 层灼烧。",
    mythTags: ["天庭"],
    style: "spell",
    grade: 2,
    effects: [
      { type: "damage", target: "allEnemies", value: 5 },
      { type: "status", target: "allEnemies", status: "burn", stacks: 5 },
    ],
  },
  fiveThunder: {
    id: "fiveThunder",
    name: "五雷正法",
    rarity: "epic",
    cost: 2,
    text: "造成 18 点伤害，抽 1 张牌，获得 1 点能量。",
    mythTags: ["天庭"],
    style: "spell",
    grade: 3,
    effects: [
      { type: "damage", target: "enemy", value: 18 },
      { type: "draw", value: 1 },
      { type: "gainEnergy", value: 1 },
    ],
  },
  starFall: {
    id: "starFall",
    name: "星落九野",
    rarity: "legendary",
    cost: 3,
    text: "对所有敌人造成 22 点伤害，施加 4 层诅咒，抽 2 张牌。",
    mythTags: ["昆仑"],
    style: "spell",
    grade: 3,
    effects: [
      { type: "damage", target: "allEnemies", value: 22 },
      { type: "status", target: "allEnemies", status: "curse", stacks: 4 },
      { type: "draw", value: 2 },
    ],
  },
  bloodNeedle: {
    id: "bloodNeedle",
    name: "血针",
    rarity: "common",
    cost: 1,
    text: "造成 3 点伤害，施加 4 层流血。",
    mythTags: ["幽冥"],
    style: "bleed",
    grade: 1,
    effects: [
      { type: "damage", target: "enemy", value: 3 },
      { type: "status", target: "enemy", status: "bleed", stacks: 4 },
    ],
  },
  bloodNet: {
    id: "bloodNet",
    name: "血网",
    rarity: "rare",
    cost: 1,
    text: "对所有敌人施加 5 层流血。",
    mythTags: ["幽冥"],
    style: "bleed",
    grade: 2,
    effects: [{ type: "status", target: "allEnemies", status: "bleed", stacks: 5 }],
  },
  bloodRiver: {
    id: "bloodRiver",
    name: "血河倒卷",
    rarity: "epic",
    cost: 2,
    text: "造成 12 点伤害，施加 10 层流血和 3 层诅咒。",
    mythTags: ["幽冥"],
    style: "bleed",
    grade: 3,
    effects: [
      { type: "damage", target: "enemy", value: 12 },
      { type: "status", target: "enemy", status: "bleed", stacks: 10 },
      { type: "status", target: "enemy", status: "curse", stacks: 3 },
    ],
  },
  asuraBlood: {
    id: "asuraBlood",
    name: "阿修罗血誓",
    rarity: "legendary",
    cost: 2,
    text: "失去 4 点生命。对所有敌人造成 10 点伤害，施加 12 层流血。",
    mythTags: ["幽冥"],
    style: "bleed",
    grade: 3,
    effects: [
      { type: "loseHp", target: "self", value: 4 },
      { type: "damage", target: "allEnemies", value: 10 },
      { type: "status", target: "allEnemies", status: "bleed", stacks: 12 },
    ],
  },
  poisonPowder: {
    id: "poisonPowder",
    name: "毒粉",
    rarity: "common",
    cost: 1,
    text: "施加 5 层毒瘴。",
    mythTags: ["山海"],
    style: "poison",
    grade: 1,
    effects: [{ type: "status", target: "enemy", status: "poison", stacks: 5 }],
  },
  centipedeJar: {
    id: "centipedeJar",
    name: "蜈蚣蛊坛",
    rarity: "rare",
    cost: 1,
    text: "造成 6 点伤害，施加 8 层毒瘴。",
    mythTags: ["山海"],
    style: "poison",
    grade: 2,
    effects: [
      { type: "damage", target: "enemy", value: 6 },
      { type: "status", target: "enemy", status: "poison", stacks: 8 },
    ],
  },
  thousandVenom: {
    id: "thousandVenom",
    name: "千毒入梦",
    rarity: "epic",
    cost: 2,
    text: "对所有敌人施加 10 层毒瘴，抽 1 张牌。",
    mythTags: ["山海"],
    style: "poison",
    grade: 3,
    effects: [
      { type: "status", target: "allEnemies", status: "poison", stacks: 10 },
      { type: "draw", value: 1 },
    ],
  },
  guKing: {
    id: "guKing",
    name: "万蛊王令",
    rarity: "legendary",
    cost: 3,
    text: "对所有敌人施加 15 层毒瘴和 3 层诅咒。",
    mythTags: ["山海"],
    style: "poison",
    grade: 3,
    effects: [
      { type: "status", target: "allEnemies", status: "poison", stacks: 15 },
      { type: "status", target: "allEnemies", status: "curse", stacks: 3 },
    ],
  },
  discordCharm: {
    id: "discordCharm",
    name: "离间符",
    rarity: "common",
    cost: 1,
    text: "施加 1 层离间。",
    mythTags: ["人间"],
    style: "control",
    grade: 1,
    effects: [{ type: "status", target: "enemy", status: "chaos", stacks: 1 }],
  },
  echoBell: {
    id: "echoBell",
    name: "回心铃",
    rarity: "rare",
    cost: 1,
    text: "对所有敌人施加 1 层离间，获得 8 点格挡。",
    mythTags: ["昆仑"],
    style: "control",
    grade: 2,
    effects: [
      { type: "status", target: "allEnemies", status: "chaos", stacks: 1 },
      { type: "block", target: "self", value: 8 },
    ],
  },
  mirrorMind: {
    id: "mirrorMind",
    name: "照心返影",
    rarity: "epic",
    cost: 2,
    text: "施加 2 层离间和 2 层诅咒，抽 1 张牌。",
    mythTags: ["天庭"],
    style: "control",
    grade: 3,
    effects: [
      { type: "status", target: "enemy", status: "chaos", stacks: 2 },
      { type: "status", target: "enemy", status: "curse", stacks: 2 },
      { type: "draw", value: 1 },
    ],
  },
  heavenlyDiscord: {
    id: "heavenlyDiscord",
    name: "天诛离魂",
    rarity: "legendary",
    cost: 3,
    text: "对所有敌人施加 2 层离间和 4 层诅咒。",
    mythTags: ["天庭"],
    style: "control",
    grade: 3,
    effects: [
      { type: "status", target: "allEnemies", status: "chaos", stacks: 2 },
      { type: "status", target: "allEnemies", status: "curse", stacks: 4 },
    ],
  },
  traceCutter: {
    id: "traceCutter",
    name: "追痕斩",
    rarity: "rare",
    cost: 1,
    text: "造成 9 点伤害。目标已有负面状态各增加 2 层。",
    mythTags: ["人间"],
    style: "physical",
    grade: 2,
    effects: [
      { type: "damage", target: "enemy", value: 9 },
      { type: "amplifyDebuffs", target: "enemy", value: 2 },
    ],
  },
  stasisCharm: {
    id: "stasisCharm",
    name: "锁脉符",
    rarity: "rare",
    cost: 1,
    text: "施加 2 层凝滞和 2 层诅咒。",
    mythTags: ["昆仑"],
    style: "control",
    grade: 2,
    effects: [
      { type: "status", target: "enemy", status: "stasis", stacks: 2 },
      { type: "status", target: "enemy", status: "curse", stacks: 2 },
    ],
  },
  bloodMonument: {
    id: "bloodMonument",
    name: "凝血成碑",
    rarity: "epic",
    cost: 2,
    text: "施加 3 层凝滞。若目标有流血，流血增加 8 层。",
    mythTags: ["幽冥"],
    style: "bleed",
    grade: 3,
    effects: [
      { type: "status", target: "enemy", status: "stasis", stacks: 3 },
      { type: "amplifyDebuffs", target: "enemy", statuses: ["bleed"], value: 8 },
    ],
  },
  venomIncense: {
    id: "venomIncense",
    name: "万毒温床",
    rarity: "epic",
    cost: 2,
    text: "施加 3 层凝滞。若目标有毒瘴，毒瘴增加 8 层。",
    mythTags: ["山海"],
    style: "poison",
    grade: 3,
    effects: [
      { type: "status", target: "enemy", status: "stasis", stacks: 3 },
      { type: "amplifyDebuffs", target: "enemy", statuses: ["poison"], value: 8 },
    ],
  },
  discordLoop: {
    id: "discordLoop",
    name: "离魂回环",
    rarity: "epic",
    cost: 2,
    text: "对所有敌人施加 2 层凝滞和 1 层离间。",
    mythTags: ["天庭"],
    style: "control",
    grade: 3,
    effects: [
      { type: "status", target: "allEnemies", status: "stasis", stacks: 2 },
      { type: "status", target: "allEnemies", status: "chaos", stacks: 1 },
    ],
  },
  doomSutra: {
    id: "doomSutra",
    name: "劫数留形",
    rarity: "legendary",
    cost: 3,
    text: "对所有敌人施加 4 层凝滞，并使已有负面状态各增加 4 层。",
    mythTags: ["洪荒"],
    style: "spell",
    grade: 3,
    effects: [
      { type: "status", target: "allEnemies", status: "stasis", stacks: 4 },
      { type: "amplifyDebuffs", target: "allEnemies", value: 4 },
    ],
  },
  gatherAsh: {
    id: "gatherAsh",
    name: "拾遗诀",
    rarity: "common",
    cost: 0,
    text: "从弃牌堆选择 1 张牌加入手牌。",
    mythTags: ["人间"],
    style: "control",
    grade: 1,
    effects: [{ type: "recoverDiscard", value: 1 }],
  },
  returnTalisman: {
    id: "returnTalisman",
    name: "归藏符",
    rarity: "rare",
    cost: 1,
    text: "从弃牌堆选择 1 张牌加入手牌，获得 1 点能量。",
    mythTags: ["昆仑"],
    style: "spell",
    grade: 2,
    effects: [
      { type: "gainEnergy", value: 1 },
      { type: "recoverDiscard", value: 1 },
    ],
  },
  cycleMandate: {
    id: "cycleMandate",
    name: "轮回敕令",
    rarity: "epic",
    cost: 2,
    text: "从弃牌堆选择 2 张牌加入手牌，抽 1 张牌。",
    mythTags: ["幽冥"],
    style: "control",
    grade: 3,
    effects: [
      { type: "draw", value: 1 },
      { type: "recoverDiscard", value: 2 },
    ],
  },
  hiddenArchive: {
    id: "hiddenArchive",
    name: "万象归藏",
    rarity: "legendary",
    cost: 3,
    text: "从弃牌堆选择 2 张牌加入手牌，获得 2 点灵气。",
    mythTags: ["洪荒"],
    style: "spell",
    grade: 3,
    effects: [
      { type: "status", target: "self", status: "spirit", stacks: 2 },
      { type: "recoverDiscard", value: 2 },
    ],
  },
};

export const enemies = {
  littleYao: {
    id: "littleYao",
    name: "小妖",
    maxHp: 22,
    intents: [{ type: "attack", value: 5, text: "扑咬 5" }],
  },
  shanxiao: {
    id: "shanxiao",
    name: "山魈",
    maxHp: 34,
    intents: [
      { type: "attack", value: 8, text: "挥爪 8" },
      { type: "block", value: 6, text: "缩身 6" },
    ],
  },
  foxYao: {
    id: "foxYao",
    name: "狐妖",
    maxHp: 28,
    intents: [
      { type: "attack", value: 4, text: "狐爪 4" },
      { type: "status", status: "burn", stacks: 3, text: "狐火 3" },
    ],
  },
  waterGhost: {
    id: "waterGhost",
    name: "水鬼",
    maxHp: 30,
    intents: [
      { type: "attack", value: 6, text: "拖拽 6" },
      { type: "status", status: "curse", stacks: 2, text: "怨念 2" },
    ],
  },
  ironCorpse: {
    id: "ironCorpse",
    name: "铁尸",
    maxHp: 45,
    intents: [
      { type: "attack", value: 10, text: "重击 10" },
      { type: "block", value: 10, text: "铁骨 10" },
    ],
  },
  blackMountain: {
    id: "blackMountain",
    name: "黑山老妖",
    maxHp: 160,
    intents: [
      { type: "attack", value: 12, text: "压顶 12" },
      { type: "attack", value: 18, text: "裂山 18" },
      { type: "block", value: 16, text: "妖雾护身 16" },
      { type: "status", status: "curse", stacks: 3, text: "黑山咒 3" },
    ],
  },
};

export const relics = {
  bloodGourd: {
    id: "bloodGourd",
    name: "血葫芦",
    rarity: "rare",
    text: "每场战斗首次击败敌人时，回复 5 点生命。",
  },
  thunderSeal: {
    id: "thunderSeal",
    name: "雷部印",
    rarity: "rare",
    text: "每回合第一次造成卡牌伤害时，额外造成 4 点伤害。",
  },
  jadeRuyi: {
    id: "jadeRuyi",
    name: "玉如意",
    rarity: "epic",
    text: "每回合开始时，获得 1 点灵气。",
  },
  ghostLantern: {
    id: "ghostLantern",
    name: "引魂灯",
    rarity: "epic",
    text: "敌人死亡时，对所有敌人施加 2 层诅咒。",
  },
  chaosFragment: {
    id: "chaosFragment",
    name: "混沌碎片",
    rarity: "legendary",
    text: "每场战斗开始时，抽 2 张牌，获得 1 点能量。",
  },
};

export const shopItems = {
  peachWine: {
    id: "peachWine",
    name: "蟠桃酒",
    price: 42,
    text: "最大生命 +8，并回复 8 点生命。",
    effects: [
      { type: "maxHp", value: 8 },
      { type: "heal", value: 8 },
    ],
  },
  spiritJade: {
    id: "spiritJade",
    name: "聚灵玉",
    price: 72,
    text: "最大能量 +1。本局最多购买一次。",
    once: true,
    effects: [{ type: "maxEnergy", value: 1 }],
  },
  greatSpiritJade: {
    id: "greatSpiritJade",
    name: "大聚灵玉",
    price: 148,
    text: "最大能量 +2。很贵，但能真正支撑三费爽牌。本局最多购买一次。",
    once: true,
    effects: [{ type: "maxEnergy", value: 2 }],
  },
  rareScroll: {
    id: "rareScroll",
    name: "灵箓残页",
    price: 48,
    text: "获得 1 张灵品以上卡牌。",
    effects: [{ type: "rareCard", value: 1 }],
  },
  doubleScroll: {
    id: "doubleScroll",
    name: "成套灵箓",
    price: 118,
    text: "获得 2 张灵品以上卡牌，适合快速补齐流派核心。",
    effects: [{ type: "rareCard", value: 2 }],
  },
  sleevePouch: {
    id: "sleevePouch",
    name: "袖里乾坤",
    price: 92,
    text: "手牌上限 +1，让保留手牌和高费牌更容易同时运转。本局最多购买一次。",
    once: true,
    effects: [{ type: "handLimit", value: 1 }],
  },
  sealBox: {
    id: "sealBox",
    name: "玄铁符匣",
    price: 58,
    text: "牌组上限 +5，并获得 20 金补贴。适合继续贪牌。",
    effects: [
      { type: "deckLimit", value: 5 },
      { type: "gold", value: 20 },
    ],
  },
  thunderTalisman: {
    id: "thunderTalisman",
    name: "雷部赦令",
    price: 96,
    text: "获得遗物雷部印。每回合第一次卡牌伤害额外造成 4 点。",
    once: true,
    effects: [{ type: "relic", value: "thunderSeal" }],
  },
  calmTea: {
    id: "calmTea",
    name: "清心茶",
    price: 35,
    text: "移除自身诅咒，并回复 6 点生命。",
    effects: [
      { type: "cleanse", status: "curse" },
      { type: "heal", value: 6 },
    ],
  },
};

export const startingDeck = [
  "strike",
  "strike",
  "strike",
  "strike",
  "strike",
  "guard",
  "guard",
  "guard",
  "guard",
  "meditate",
];
